name: calendar_test_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  table_calendar: ^3.2.0
  fl_chart: ^0.66.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/pics/
    - assets/icons/